CREATE FUNCTION public.handle_new_user() RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER
    AS $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$;

CREATE TABLE public.comment (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    product_id bigint,
    user_id uuid DEFAULT gen_random_uuid(),
    content text
);

ALTER TABLE public.comment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.product (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    name text,
    price numeric,
    image_url text,
    in_stock boolean,
    description text,
    category text
);

ALTER TABLE public.product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.profiles (
    id uuid NOT NULL,
    updated_at timestamp with time zone,
    username text,
    avatar_url text,
    website text,
    full_name text,
    CONSTRAINT username_length CHECK ((char_length(username) >= 3))
);

INSERT INTO public.product (id, created_at, name, price, image_url, in_stock, description, category) VALUES ('3', '2025-01-26 12:41:43.391356+00', 'Laptop', '1200', 'https://goopddlaqkruiqmxpjyj.supabase.co/storage/v1/object/public/images_retail/Laptop1.jpg', 't', 'Laptop is a high-quality product with a competitive price of $1200.', 'electronics');

INSERT INTO public.product (id, created_at, name, price, image_url, in_stock, description, category) VALUES ('5', '2025-01-26 12:41:43.391391+00', 'Laptop', '1200', 'https://goopddlaqkruiqmxpjyj.supabase.co/storage/v1/object/public/images_retail/Laptop1.jpg', 't', 'Laptop is a high-quality product with a competitive price of $1200.', 'electronics');

INSERT INTO public.product (id, created_at, name, price, image_url, in_stock, description, category) VALUES ('2', '2025-01-26 12:41:43.391337+00', 'Laptop', '1200', 'https://goopddlaqkruiqmxpjyj.supabase.co/storage/v1/object/public/images_retail/Laptop1.jpg', 't', 'Laptop is a high-quality product with a competitive price of $1200.', 'electronics');

INSERT INTO public.product (id, created_at, name, price, image_url, in_stock, description, category) VALUES ('1', '2025-01-26 12:41:43.391306+00', 'TV', '300', 'https://goopddlaqkruiqmxpjyj.supabase.co/storage/v1/object/public/images_retail/TV.jpg', 't', 'TV is a high-quality product with a competitive price of $300.', 'electronics');

INSERT INTO public.product (id, created_at, name, price, image_url, in_stock, description, category) VALUES ('14', '2025-01-26 12:41:43.391553+00', 'Laptop', '700', 'https://goopddlaqkruiqmxpjyj.supabase.co/storage/v1/object/public/images_retail/Laptop2.jpg', 't', 'Laptop is a high-quality product with a competitive price of $700.', 'electronics');

INSERT INTO public.product (id, created_at, name, price, image_url, in_stock, description, category) VALUES ('16', '2025-01-26 12:41:43.391586+00', 'Laptop', '700', 'https://goopddlaqkruiqmxpjyj.supabase.co/storage/v1/object/public/images_retail/Laptop2.jpg', 't', 'Laptop is a high-quality product with a competitive price of $700.', 'electronics');

INSERT INTO public.product (id, created_at, name, price, image_url, in_stock, description, category) VALUES ('15', '2025-01-26 12:41:43.39157+00', 'Laptop', '700', 'https://goopddlaqkruiqmxpjyj.supabase.co/storage/v1/object/public/images_retail/Laptop2.jpg', 't', 'Laptop is a high-quality product with a competitive price of $700.', 'electronics');

INSERT INTO public.product (id, created_at, name, price, image_url, in_stock, description, category) VALUES ('13', '2025-01-26 12:41:43.391536+00', 'Laptop', '700', 'https://goopddlaqkruiqmxpjyj.supabase.co/storage/v1/object/public/images_retail/Laptop2.jpg', 't', 'Laptop is a high-quality product with a competitive price of $700.', 'electronics');

INSERT INTO public.product (id, created_at, name, price, image_url, in_stock, description, category) VALUES ('12', '2025-01-26 12:41:43.391518+00', 'Laptop', '700', 'https://goopddlaqkruiqmxpjyj.supabase.co/storage/v1/object/public/images_retail/Laptop2.jpg', 't', 'Laptop is a high-quality product with a competitive price of $700.', 'electronics');

INSERT INTO public.product (id, created_at, name, price, image_url, in_stock, description, category) VALUES ('11', '2025-01-26 12:41:43.391501+00', 'Laptop', '700', 'https://goopddlaqkruiqmxpjyj.supabase.co/storage/v1/object/public/images_retail/Laptop2.jpg', 't', 'Laptop is a high-quality product with a competitive price of $700.', 'electronics');

INSERT INTO public.product (id, created_at, name, price, image_url, in_stock, description, category) VALUES ('10', '2025-01-26 12:41:43.391483+00', 'Laptop', '700', 'https://goopddlaqkruiqmxpjyj.supabase.co/storage/v1/object/public/images_retail/Laptop2.jpg', 't', 'Laptop is a high-quality product with a competitive price of $700.', 'electronics');

INSERT INTO public.product (id, created_at, name, price, image_url, in_stock, description, category) VALUES ('9', '2025-01-26 12:41:43.391464+00', 'Laptop', '700', 'https://goopddlaqkruiqmxpjyj.supabase.co/storage/v1/object/public/images_retail/Laptop2.jpg', 't', 'Laptop is a high-quality product with a competitive price of $700.', 'electronics');

INSERT INTO public.product (id, created_at, name, price, image_url, in_stock, description, category) VALUES ('8', '2025-01-26 12:41:43.391445+00', 'Laptop', '1200', 'https://goopddlaqkruiqmxpjyj.supabase.co/storage/v1/object/public/images_retail/Laptop1.jpg', 't', 'Laptop is a high-quality product with a competitive price of $1200.', 'electronics');

INSERT INTO public.product (id, created_at, name, price, image_url, in_stock, description, category) VALUES ('7', '2025-01-26 12:41:43.391425+00', 'Laptop', '1200', 'https://goopddlaqkruiqmxpjyj.supabase.co/storage/v1/object/public/images_retail/Laptop1.jpg', 't', 'Laptop is a high-quality product with a competitive price of $1200.', 'electronics');

INSERT INTO public.product (id, created_at, name, price, image_url, in_stock, description, category) VALUES ('6', '2025-01-26 12:41:43.391407+00', 'Laptop', '1200', 'https://goopddlaqkruiqmxpjyj.supabase.co/storage/v1/object/public/images_retail/Laptop1.jpg', 't', 'Laptop is a high-quality product with a competitive price of $1200.', 'electronics');

INSERT INTO public.product (id, created_at, name, price, image_url, in_stock, description, category) VALUES ('4', '2025-01-26 12:41:43.391374+00', 'Laptop', '1200', 'https://goopddlaqkruiqmxpjyj.supabase.co/storage/v1/object/public/images_retail/Laptop1.jpg', 't', 'Laptop is a high-quality product with a competitive price of $1200.', 'electronics');

SELECT pg_catalog.setval('public.comment_id_seq', 1, false);

SELECT pg_catalog.setval('public.product_id_seq', 1, false);

ALTER TABLE ONLY public.comment
    ADD CONSTRAINT comment_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.product
    ADD CONSTRAINT product_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT profiles_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT profiles_username_key UNIQUE (username);

CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

ALTER TABLE ONLY public.comment
    ADD CONSTRAINT comment_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.product(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY public.comment
    ADD CONSTRAINT comment_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;

CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles FOR SELECT USING (true);

CREATE POLICY "Users can insert their own profile." ON public.profiles FOR INSERT WITH CHECK ((( SELECT auth.uid() AS uid) = id));

CREATE POLICY "Users can update own profile." ON public.profiles FOR UPDATE USING ((( SELECT auth.uid() AS uid) = id));

ALTER TABLE public.comment ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

GRANT USAGE ON SCHEMA public TO postgres;

GRANT USAGE ON SCHEMA public TO anon;

GRANT USAGE ON SCHEMA public TO authenticated;

GRANT USAGE ON SCHEMA public TO service_role;

GRANT ALL ON FUNCTION public.handle_new_user() TO anon;

GRANT ALL ON FUNCTION public.handle_new_user() TO authenticated;

GRANT ALL ON FUNCTION public.handle_new_user() TO service_role;

GRANT ALL ON TABLE public.comment TO anon;

GRANT ALL ON TABLE public.comment TO authenticated;

GRANT ALL ON TABLE public.comment TO service_role;

GRANT ALL ON SEQUENCE public.comment_id_seq TO anon;

GRANT ALL ON SEQUENCE public.comment_id_seq TO authenticated;

GRANT ALL ON SEQUENCE public.comment_id_seq TO service_role;

GRANT ALL ON TABLE public.product TO anon;

GRANT ALL ON TABLE public.product TO authenticated;

GRANT ALL ON TABLE public.product TO service_role;

GRANT ALL ON SEQUENCE public.product_id_seq TO anon;

GRANT ALL ON SEQUENCE public.product_id_seq TO authenticated;

GRANT ALL ON SEQUENCE public.product_id_seq TO service_role;

GRANT ALL ON TABLE public.profiles TO anon;

GRANT ALL ON TABLE public.profiles TO authenticated;

GRANT ALL ON TABLE public.profiles TO service_role;
